<cfheader statuscode="403" statustext="forbidden">
<cfoutput>
	<main class="container" id="content">
		<div class="row">
			<div class="col-8 mx-auto pt-5">
				<h1 class="h2">403: Forbidden</h1>
				<p>#cgi.redirect_url# is not a valid request. It may be something that your browser or an add-on is
				requesting, or it may be malicious code running from your computer.
				</p>
				<p>
					Please <a href="/contact.cfm">contact us</a> if you feel you should not be receiving this message.
				</p>
				<cftry>
				<cfif NOT isDefined("clientAddress")>
					<cfinclude template="/shared/component/clientAddress.cfc" runOnce="true">
				</cfif>
				<cfif NOT isDefined("allowAlertMail")>
					<cfinclude template="/shared/component/mailThrottle.cfc" runOnce="true">
				</cfif>
				<cfset ipaddress = clientAddress()>
				<cfif allowAlertMail("forbidden", ipaddress)>
				<cfmail subject="403: Forbidden" to="#Application.PageProblemEmail#" from="forbidden@#application.fromEmail#" type="html">
					A user found a dead link! The referring site was #encodeForHtml(cgi.HTTP_REFERER)#.
					<cfif isdefined("CGI.script_name")>
						<br>The missing page is #encodeForHtml(Replace(CGI.script_name, "/", ""))#
					</cfif>
					<cfif isdefined("cgi.REDIRECT_URL")>
						<br>cgi.REDIRECT_URL: #encodeForHtml(cgi.REDIRECT_URL)#
					</cfif>
					<cfif isdefined("session.username")>
						<br>The username is #encodeForHtml(session.username)#
					</cfif>
					<br>The IP requesting the dead link was <a href="http://network-tools.com/default.asp?prog=network&host=#encodeForUrl(ipaddress)#">#encodeForHtml(ipaddress)#</a>
					 - <a href="#Application.serverRootUrl#/Admin/blacklist.cfm">blocklist</a>
					<br>This message was generated by #cgi.CF_TEMPLATE_PATH#.
					<!--- Not the whole cgi scope: its Cookie header carries the CFID, which decrypts session.epw. --->
					<br>Query string: #encodeForHtml(REReplaceNoCase(cgi.query_string, "((pass|pwd|password|token|cfid|cftoken|jsessionid)[a-z_]*=)[^&]*", "\1[redacted]", "all"))#
					<br>User agent: #encodeForHtml(cgi.http_user_agent)#
				</cfmail>
				</cfif>
				<cfcatch>
					<p>Error in sending mail.</p>
				</cfcatch>
				</cftry>
			</div>
		</div>
	</main>
</cfoutput>
