<!--- Blocks the client making the current request.  Only for inclusion by pages that detect a
	probe; a direct request is answered as not found. --->
<cfif getFileFromPath(getBaseTemplatePath()) EQ "autoblacklist.cfm">
	<cfheader statuscode="404" statustext="Not Found">
	<cfabort>
</cfif>
<!--- also included from Application.cfc onMissingTemplate, where the functions are already defined --->
<cfif NOT isDefined("clientAddress")>
	<cfinclude template="/shared/component/clientAddress.cfc" runOnce="true">
</cfif>
<cfset ipaddress = clientAddress()>
	<cftry>
		<cfset inserted = false>
		<cfset notInsertedReason = "">
		<cfif NOT isIpAddress(ipaddress)>
			<cfset notInsertedReason = "not a single IP address">
		<cfelseif isBlockExempt(ipaddress)>
			<!--- blocking a proxy or this server would block every user --->
			<cfset notInsertedReason = "exempt (this server, a trusted proxy, or an exempt address)">
		<cfelse>
			<cfquery name="d" datasource="uam_god">
				INSERT INTO mczbase.blacklist 
					(ip) 
				VALUES 
					(<cfqueryparam CFSQLTYPE="CF_SQL_VARCHAR" value="#ipaddress#">)
			</cfquery>
			<cfset inserted = true>
			<cfset application.blacklist=listappend(application.blacklist,ipaddress)>
		</cfif>
		<cfmail subject="Autoblacklist Success" to="#Application.PageProblemEmail#" from="blacklisted@#application.fromEmail#" type="html">
			MCZbase automatically blacklisted IP
			<cfif inserted>
			<a href="http://network-tools.com/default.asp?prog=network&host=#encodeForUrl(ipaddress)#">#encodeForHtml(ipaddress)#</a>
			- <a href="#application.serverRootUrl#/Admin/blacklist.cfm">blocklist</a>
			<cfelse>
				Not added to blacklist table: #encodeForHtml(ipaddress)#, #encodeForHtml(notInsertedReason)#
			</cfif>
			<br>Remote address: #encodeForHtml(cgi.remote_addr)#, forwarded for: #encodeForHtml(cgi.http_x_forwarded_for)#
			<p></p>
			<!--- No cgi, url, form or session dumps: the Cookie header carries the CFID, which decrypts
				session.epw, and forms may carry passwords. --->
			<br>Page: #encodeForHtml(cgi.script_name)#
			<br>Query string: #encodeForHtml(REReplaceNoCase(cgi.query_string, "((pass|pwd|password|token|cfid|cftoken|jsessionid)[a-z_]*=)[^&]*", "\1[redacted]", "all"))#
			<br>Referrer: #encodeForHtml(cgi.http_referer)#
			<br>User agent: #encodeForHtml(cgi.http_user_agent)#
			<cfif isDefined("session.username")>
				<br>Username: #encodeForHtml(session.username)#
			</cfif>
		</cfmail>
		<cfinclude template="/errors/gtfo.cfm">
		<script>
			try{document.getElementById('loading').style.display='none';}catch(e){}
		</script>
		<cfabort>
		<cfcatch>
			<cfmail subject="Autoblacklist Fail" to="#Application.PageProblemEmail#" from="blfail@#application.fromEmail#" type="html">
				Auto-blacklisting failed.
				<br>
				A user found a dead link! The referring site was #cgi.HTTP_REFERER#.
				<cfif isdefined("CGI.script_name")>
					<br>The missing page is #Replace(CGI.script_name, "/", "")#
				</cfif>
				<cfif isdefined("cgi.REDIRECT_URL")>
					<br>cgi.REDIRECT_URL: #cgi.REDIRECT_URL#
				</cfif>
				<cfif isdefined("session.username")>
					<br>The username is #session.username#
				</cfif>
				<br>The IP requesting the dead link was <a href="http://network-tools.com/default.asp?prog=network&host=#encodeForUrl(ipaddress)#">#encodeForHtml(ipaddress)#</a>
				 - <a href="#application.serverRootUrl#/Admin/blacklist.cfm">blocklist</a>
				<br>This message was generated by #cgi.CF_TEMPLATE_PATH#.
				<br>Query string: #encodeForHtml(REReplaceNoCase(cgi.query_string, "((pass|pwd|password|token|cfid|cftoken|jsessionid)[a-z_]*=)[^&]*", "\1[redacted]", "all"))#
				<br>User agent: #encodeForHtml(cgi.http_user_agent)#
			</cfmail>
		</cfcatch>
	</cftry>
