<!---
tools/searchSqlDump.cfm

Copyright 2026 President and Fellows of Harvard College

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

--->
<!--- Redmine 1031 phase 1 regression harness, single criteria set.

	Seeds the caller variables the way SpecimenResults.cfm does, includes
	/includes/SearchSql.cfm with whatever search criteria arrive in the query string, and
	prints the resulting SQL fragments and bind parameters as plain text.  It NEVER executes
	the assembled SQL.

	Purpose: capture a "before" baseline for every criteria combination in the corpus, then
	capture an "after" baseline once the include has been parameterized, and diff the two.
	With roughly 140 independent criteria blocks in SearchSql.cfm, behaviour preservation
	cannot be established by reading a diff of the source.

	Usage: append the criteria to the query string exactly as SpecimenResults.cfm receives
	them, for example
		/tools/searchSqlDump.cfm?dumpLabel=before&catnum=1-5&country=Peru

	Output is whitespace normalized so that the reformatting phase 3 inevitably causes does
	not swamp the diff with noise.  BEGIN and END markers bracket the report: SearchSql.cfm
	calls <cfabort> on some invalid input, so a report with no END marker means the include
	aborted, which the driver reports as ABORTED rather than silently accepting a short file.

	Notes on fidelity:
	- Criteria are read from the url scope by SearchSql.cfm's own isdefined("name") calls.
	  This page deliberately does NOT <cfparam> them: defining all 163 names would make
	  isdefined() true for every one and change which blocks fire.  Phase 5 of Redmine 1031
	  corrects the scope handling in SearchSql.cfm and in this harness together.
	- checkSql() is deliberately not called here.  It contributes nothing to the dump and on
	  a hit it includes /errors/autoblacklist.cfm, which would blacklist the running user.
	- basSelect is fixed rather than built from cf_spec_res_cols and session.resultColumnList,
	  so the diff isolates the criteria assembly rather than each user's column preferences.
	- session.flatTableName differs by user class: FLAT for internal users, FILTERED_FLAT for
	  external.  SearchSql.cfm never branches on its value, only interpolates it as an
	  identifier, so the two classes' SQL differs by that token alone.  A baseline is
	  therefore valid as long as the before and after runs use the same user class, which is
	  why the class is recorded in the report header.
--->
<cfsetting enablecfoutputonly="true">
<cfcontent type="text/plain; charset=utf-8">
<cfinclude template="/includes/functionLib.cfm">

<cfparam name="url.dumpLabel" default="unlabelled">

<cfif NOT (isDefined("session.roles") AND listContainsNoCase(session.roles,"manage_specimens"))>
	<!--- extra check to ensure access only by authorized users --->
	<cfthrow message="Inadequate Permissions.">
</cfif>

<!--- The flat table name is an identifier and cannot be bound, so whitelist it here exactly as
	phase 4 will at the six include sites. --->
<cfset variables.FLAT_TABLE_ALLOWED = "flat,filtered_flat">
<cfif NOT isDefined("session.flatTableName")>
	<cfthrow message="session.flatTableName is not set. Log in before running the harness.">
</cfif>
<cfset variables.flatTable = lcase(session.flatTableName)>
<cfif NOT listFindNoCase(variables.FLAT_TABLE_ALLOWED,variables.flatTable)>
	<cfthrow message="Unexpected value for session.flatTableName: not one of #variables.FLAT_TABLE_ALLOWED#.">
</cfif>

<cfset variables.showObservations = "not set">
<cfif isDefined("session.ShowObservations")>
	<cfset variables.showObservations = session.ShowObservations>
</cfif>
<cfset variables.sessionCollection = "not set">
<cfif isDefined("session.collection")>
	<cfset variables.sessionCollection = session.collection>
</cfif>
<cfset variables.sessionRoles = "not set">
<cfif isDefined("session.roles")>
	<cfset variables.sessionRoles = session.roles>
</cfif>

<!--- Emit the header before including SearchSql.cfm so that an abort inside the include still
	leaves enough context in the output to identify which corpus entry failed. --->
<cfoutput>=== MCZbase SearchSql dump BEGIN ===
dumpLabel: #url.dumpLabel#
flatTableName: #variables.flatTable#
session.roles: #variables.sessionRoles#
session.ShowObservations: #variables.showObservations#
session.collection: #variables.sessionCollection#
query_string: #cgi.query_string#
</cfoutput>

<!--- The report body is generated by a shared include so that this page and the in process
	path in /tools/searchSqlBaseline.cfm produce byte identical output.  A hash of that output
	is what before and after baselines are compared on, so the two must not drift apart. --->
<cfinclude template="/tools/searchSqlDumpBody.cfm">

<cfoutput>
=== MCZbase SearchSql dump END ===
</cfoutput>
