<!---
tools/searchSqlBaseline.cfm

Copyright 2026 President and Fellows of Harvard College

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

--->
<!--- Redmine 1031 phase 1 regression harness, corpus driver.

	Runs /tools/searchSqlDump.cfm once per corpus entry and writes each report to its own
	file, so that the SQL generated by /includes/SearchSql.cfm before parameterization can be
	diffed against the SQL generated after.

	Corpus: the saved searches in cf_canned_search whose URL targets SpecimenResults.cfm.
	These are real parameter combinations that real users saved, which is the point -- they
	include combinations nobody would think to write a test for.  Additional URLs, for example
	harvested from web server logs, can be pasted into the form.

	Each entry is fetched as a separate HTTP request rather than by including SearchSql.cfm in
	a loop.  Two reasons: the include leaves roughly 163 criteria variables in the variables
	scope, so a second iteration would inherit the first entry's criteria; and SearchSql.cfm
	calls <cfabort> on some invalid input, which would end the whole run.  A separate request
	per entry gives each one a clean scope, and an abort affects only that entry.

	Workflow:
	  1. Run with dumpLabel=before on an unmodified checkout.
	  2. Do the phase 3 work.
	  3. Run with dumpLabel=after.
	  4. diff -r the two output directories.
	Use the same login for both runs: session.flatTableName is FLAT for internal users and
	FILTERED_FLAT for external ones, and that token appears throughout the generated SQL.
--->
<cfset pageTitle="Redmine 1031 Phase 1 Baseline Capture">
<cfinclude template="/shared/_header.cfm">
<cfif NOT (isDefined("session.roles") AND listContainsNoCase(session.roles,"manage_specimens"))>
	<!--- extra check to ensure access only by authorized users --->
	<cfthrow message="Inadequate Permissions.">
</cfif>

<!--- Obtain parameters with explicit scopes, form taking priority over url. --->
<cfparam name="url.dumpLabel" default="before">
<cfparam name="form.dumpLabel" default="">
<cfparam name="url.action" default="list">
<cfparam name="form.action" default="">
<cfparam name="url.baseUrl" default="">
<cfparam name="form.baseUrl" default="">
<cfparam name="url.outputDir" default="">
<cfparam name="form.outputDir" default="">
<cfparam name="url.maxEntries" default="0">
<cfparam name="form.maxEntries" default="">
<cfparam name="form.extraUrls" default="">

<cfset variables.dumpLabel = url.dumpLabel>
<cfif len(form.dumpLabel) GT 0><cfset variables.dumpLabel = form.dumpLabel></cfif>
<cfset variables.action = url.action>
<cfif len(form.action) GT 0><cfset variables.action = form.action></cfif>
<cfset variables.baseUrl = url.baseUrl>
<cfif len(form.baseUrl) GT 0><cfset variables.baseUrl = form.baseUrl></cfif>
<cfif len(variables.baseUrl) EQ 0><cfset variables.baseUrl = Application.serverRootUrl></cfif>
<cfset variables.outputDir = url.outputDir>
<cfif len(form.outputDir) GT 0><cfset variables.outputDir = form.outputDir></cfif>
<cfif len(variables.outputDir) EQ 0>
	<cfset variables.outputDir = getTempDirectory() & "searchSqlBaseline">
</cfif>
<cfset variables.maxEntries = url.maxEntries>
<cfif len(form.maxEntries) GT 0><cfset variables.maxEntries = form.maxEntries></cfif>
<cfif NOT isNumeric(variables.maxEntries)><cfset variables.maxEntries = 0></cfif>

<!--- Label becomes a directory name, so restrict it to characters safe in a path. --->
<cfif REFind("^[A-Za-z0-9_\-]{1,40}$",variables.dumpLabel) EQ 0>
	<cfthrow message="dumpLabel must be 1 to 40 characters of letters, digits, underscore or hyphen.">
</cfif>
<cfset variables.runDir = variables.outputDir & "/" & variables.dumpLabel>

<!--- Fetching the whole corpus takes a while; one request per entry. --->
<cfsetting requesttimeout="1800">

<cfquery name="corpus" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,cookie.cfid)#" timeout="#Application.query_timeout#" result="corpus_result">
	SELECT
		cf_canned_search.canned_id,
		cf_canned_search.search_name,
		cf_canned_search.url
	FROM
		cf_canned_search
		JOIN cf_users ON (cf_users.user_id = cf_canned_search.user_id)
	WHERE
		cf_canned_search.url LIKE <cfqueryparam cfsqltype="CF_SQL_VARCHAR" value="%SpecimenResults.cfm%">
	ORDER BY
		cf_canned_search.canned_id
</cfquery>

<!--- Build the working corpus: saved searches, plus any pasted URLs. --->
<cfset variables.entries = arrayNew(1)>
<cfloop query="corpus">
	<cfset arrayAppend(variables.entries,{
		source = "cf_canned_search",
		id = corpus.canned_id,
		name = corpus.search_name,
		url = corpus.url
	})>
</cfloop>
<cfif len(trim(form.extraUrls)) GT 0>
	<cfset variables.extraSeq = 0>
	<cfloop list="#form.extraUrls#" delimiters="#chr(10)##chr(13)#" index="variables.extraUrl">
		<cfif len(trim(variables.extraUrl)) GT 0>
			<cfset variables.extraSeq = variables.extraSeq + 1>
			<cfset arrayAppend(variables.entries,{
				source = "pasted",
				id = "x#variables.extraSeq#",
				name = "pasted entry #variables.extraSeq#",
				url = trim(variables.extraUrl)
			})>
		</cfif>
	</cfloop>
</cfif>
<cfif variables.maxEntries GT 0 AND arrayLen(variables.entries) GT variables.maxEntries>
	<cfset variables.entries = arraySlice(variables.entries,1,variables.maxEntries)>
</cfif>

<!--- Function queryStringOf extracts the query string from a stored search URL.

	@param storedUrl a URL as saved in cf_canned_search, which may or may not carry a scheme
		and host, and may or may not carry a leading question mark.
	@return everything after the first question mark, or an empty string if there is none.
--->
<cffunction name="queryStringOf" access="private" returntype="string" output="false">
	<cfargument name="storedUrl" type="string" required="yes">
	<cfset var markAt = find("?",arguments.storedUrl)>

	<cfif markAt EQ 0>
		<cfreturn "">
	</cfif>
	<cfreturn right(arguments.storedUrl,len(arguments.storedUrl) - markAt)>
</cffunction>

<cfset variables.runResults = arrayNew(1)>

<cfif variables.action EQ "capture">
	<cfdirectory action="create" directory="#variables.runDir#" mode="770" storeacl="no">
	<cfset variables.seq = 0>
	<cfset variables.manifest = "seq" & chr(9) & "source" & chr(9) & "id" & chr(9) & "status" & chr(9) & "httpStatus" & chr(9) & "file" & chr(9) & "url" & chr(10)>
	<cfloop array="#variables.entries#" index="variables.entry">
		<cfset variables.seq = variables.seq + 1>
		<cfset variables.qs = queryStringOf(variables.entry.url)>
		<cfset variables.outFile = numberFormat(variables.seq,"0000") & "_" & variables.entry.id & ".txt">
		<cfset variables.status = "UNKNOWN">
		<cfset variables.httpStatus = "">
		<cfset variables.body = "">
		<cfif len(variables.qs) EQ 0>
			<cfset variables.status = "NO_CRITERIA">
			<cfset variables.body = "Stored URL carried no query string, nothing to dump." & chr(10) & variables.entry.url>
		<cfelse>
			<cftry>
				<cfset variables.target = variables.baseUrl & "/tools/searchSqlDump.cfm?dumpLabel=" & encodeForUrl(variables.dumpLabel) & "&" & variables.qs>
				<cfhttp url="#variables.target#" method="get" charset="utf-8" timeout="120" throwonerror="false" result="dumpCall">
					<!--- Forward the session identifiers so the child request runs as this user and
						therefore sees the same session.flatTableName, roles and credentials. --->
					<cfhttpparam type="cookie" name="cfid" value="#cookie.cfid#">
					<cfhttpparam type="cookie" name="cftoken" value="#cookie.cftoken#">
				</cfhttp>
				<cfset variables.httpStatus = dumpCall.statusCode>
				<cfset variables.body = dumpCall.fileContent>
				<cfif left(variables.httpStatus,3) NEQ "200">
					<cfset variables.status = "HTTP_ERROR">
				<cfelseif findNoCase("=== MCZbase SearchSql dump END ===",variables.body) GT 0>
					<cfset variables.status = "OK">
				<cfelse>
					<!--- SearchSql.cfm aborted, most likely on input it rejects as invalid. --->
					<cfset variables.status = "ABORTED">
				</cfif>
			<cfcatch>
				<cfset variables.status = "FETCH_ERROR">
				<cfset variables.body = "#cfcatch.message# #cfcatch.detail#">
			</cfcatch>
			</cftry>
		</cfif>
		<cffile action="write" file="#variables.runDir#/#variables.outFile#" output="#variables.body#" charset="utf-8" addnewline="no">
		<cfset variables.manifest = variables.manifest & variables.seq & chr(9) & variables.entry.source & chr(9) & variables.entry.id & chr(9) & variables.status & chr(9) & variables.httpStatus & chr(9) & variables.outFile & chr(9) & variables.entry.url & chr(10)>
		<cfset arrayAppend(variables.runResults,{
			seq = variables.seq,
			id = variables.entry.id,
			name = variables.entry.name,
			status = variables.status,
			httpStatus = variables.httpStatus,
			outFile = variables.outFile
		})>
	</cfloop>
	<cffile action="write" file="#variables.runDir#/manifest.tsv" output="#variables.manifest#" charset="utf-8" addnewline="no">
</cfif>

<cfoutput>
<main class="container py-3" id="content">
	<section class="row border rounded my-2 p-2">
		<div class="col-12 pt-2">
			<h1 class="h2">Redmine 1031 Phase 1 Baseline Capture</h1>
			<p>
				Runs <code>/tools/searchSqlDump.cfm</code> once per saved search and writes each
				report to a file, so the SQL generated before parameterizing
				<code>/includes/SearchSql.cfm</code> can be diffed against the SQL generated after.
				Nothing here executes the assembled search SQL.
			</p>
			<p class="mb-1">
				<strong>Capture <code>before</code> on an unmodified checkout, then <code>after</code> once
				phase 3 is done, using the same login both times.</strong>
				<code>session.flatTableName</code> is <code>FLAT</code> for internal users and
				<code>FILTERED_FLAT</code> for external ones, and that token appears throughout the
				generated SQL.
			</p>
			<p>
				This session would capture as: <strong>#encodeForHtml(session.flatTableName)#</strong>
			</p>
			<form name="capture" id="capture" method="post" action="/tools/searchSqlBaseline.cfm">
				<input type="hidden" name="action" id="action" value="capture">
				<div class="form-row">
					<div class="col-12 col-md-3">
						<label for="dumpLabel" class="data-entry-label">Run label (directory name)</label>
						<input type="text" name="dumpLabel" id="dumpLabel" class="data-entry-input mb-1" value="#encodeForHtml(variables.dumpLabel)#" required pattern="[A-Za-z0-9_\-]{1,40}">
					</div>
					<div class="col-12 col-md-3">
						<label for="maxEntries" class="data-entry-label">Max entries (0 for all)</label>
						<input type="text" name="maxEntries" id="maxEntries" class="data-entry-input mb-1" value="#encodeForHtml(variables.maxEntries)#">
					</div>
					<div class="col-12 col-md-6">
						<label for="outputDir" class="data-entry-label">Output directory</label>
						<input type="text" name="outputDir" id="outputDir" class="data-entry-input mb-1" value="#encodeForHtml(variables.outputDir)#">
					</div>
				</div>
				<div class="form-row">
					<div class="col-12 col-md-6">
						<label for="baseUrl" class="data-entry-label">Base URL for self requests</label>
						<input type="text" name="baseUrl" id="baseUrl" class="data-entry-input mb-1" value="#encodeForHtml(variables.baseUrl)#">
						<small class="text-secondary">If the server cannot verify its own certificate, use http://127.0.0.1 here.</small>
					</div>
					<div class="col-12 col-md-6">
						<label for="extraUrls" class="data-entry-label">Additional URLs, one per line (optional)</label>
						<textarea name="extraUrls" id="extraUrls" class="data-entry-input mb-1" rows="4">#encodeForHtml(form.extraUrls)#</textarea>
						<small class="text-secondary">For example harvested from web server logs. Only the query string is used.</small>
					</div>
				</div>
				<button type="submit" class="btn btn-xs btn-primary mt-2">Capture baseline</button>
			</form>
		</div>
	</section>

	<cfif variables.action EQ "capture">
		<section class="row border rounded my-2 p-2">
			<div class="col-12 pt-2">
				<h2 class="h3">Run results</h2>
				<p>
					Wrote #arrayLen(variables.runResults)# report(s) plus <code>manifest.tsv</code> to
					<code>#encodeForHtml(variables.runDir)#</code>
				</p>
				<cfset variables.countOk = 0>
				<cfset variables.countAborted = 0>
				<cfset variables.countOther = 0>
				<cfloop array="#variables.runResults#" index="variables.row">
					<cfif variables.row.status EQ "OK"><cfset variables.countOk = variables.countOk + 1>
					<cfelseif variables.row.status EQ "ABORTED"><cfset variables.countAborted = variables.countAborted + 1>
					<cfelse><cfset variables.countOther = variables.countOther + 1>
					</cfif>
				</cfloop>
				<p>
					OK: #variables.countOk# &nbsp; Aborted by SearchSql.cfm: #variables.countAborted#
					&nbsp; Other: #variables.countOther#
				</p>
				<p class="small text-secondary">
					To compare two runs on the server:
					<code>diff -r #encodeForHtml(variables.outputDir)#/before #encodeForHtml(variables.outputDir)#/after</code>
				</p>
				<table class="table table-responsive table-striped d-xl-table">
					<thead class="thead-light">
						<tr>
							<th>##</th>
							<th>Status</th>
							<th>HTTP</th>
							<th>Saved search</th>
							<th>File</th>
						</tr>
					</thead>
					<tbody>
						<cfloop array="#variables.runResults#" index="variables.row">
							<cfset variables.statusClass = "">
							<cfif variables.row.status EQ "OK"><cfset variables.statusClass = "text-success"></cfif>
							<cfif variables.row.status EQ "ABORTED"><cfset variables.statusClass = "text-warning font-weight-bold"></cfif>
							<cfif listFindNoCase("HTTP_ERROR,FETCH_ERROR",variables.row.status)><cfset variables.statusClass = "text-danger font-weight-bold"></cfif>
							<tr>
								<td>#variables.row.seq#</td>
								<td class="#variables.statusClass#">#encodeForHtml(variables.row.status)#</td>
								<td>#encodeForHtml(variables.row.httpStatus)#</td>
								<td>#encodeForHtml(variables.row.name)#</td>
								<td>#encodeForHtml(variables.row.outFile)#</td>
							</tr>
						</cfloop>
					</tbody>
				</table>
			</div>
		</section>
	<cfelse>
		<section class="row border rounded my-2 mb-4 p-2">
			<div class="col-12 pt-2">
				<h2 class="h3">Corpus preview: #arrayLen(variables.entries)# entr#iif(arrayLen(variables.entries) EQ 1,DE("y"),DE("ies"))#</h2>
				<p>Saved searches in <code>cf_canned_search</code> targeting SpecimenResults.cfm. Nothing has been fetched or written yet.</p>
				<table class="table table-responsive table-striped d-xl-table">
					<thead class="thead-light">
						<tr><th>##</th><th>Source</th><th>id</th><th>Saved search</th><th>Criteria</th></tr>
					</thead>
					<tbody>
						<cfset variables.previewSeq = 0>
						<cfloop array="#variables.entries#" index="variables.entry">
							<cfset variables.previewSeq = variables.previewSeq + 1>
							<tr>
								<td>#variables.previewSeq#</td>
								<td>#encodeForHtml(variables.entry.source)#</td>
								<td>#encodeForHtml(variables.entry.id)#</td>
								<td>#encodeForHtml(variables.entry.name)#</td>
								<td class="small">#encodeForHtml(queryStringOf(variables.entry.url))#</td>
							</tr>
						</cfloop>
					</tbody>
				</table>
			</div>
		</section>
	</cfif>
</main>
</cfoutput>
<cfinclude template="/shared/_footer.cfm">
