<!--

* /metrics/testMetrics.cfm

Copyright 2023 President and Fellows of Harvard College

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

* Demonstration of ajax patterns in MCZbase.

-->
<cfset pageTitle="Metrics Testing">
<cfinclude template="/shared/_header.cfm">
<cfinclude template = "/shared/component/functions.cfc">

<cfset targetFile = "chart_data.csv">
<cfset filePath = "/metrics/datafiles/">

<cfquery name="getStats" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,cfid)#">
select f.COLLECTION, ts.CATEGORY as "CITATION_TYPE",ts.type_status, count(distinct f.collection_object_id) as "NUMBER_OF_CITATIONS", count(distinct media_id) as "NUMBER_OF_IMAGES", 
count(distinct mr.related_primary_key) as "NUMBER_OF_TYPES_WITH_IMAGES", to_char(co.coll_object_entered_date,'YYYY') as "ENTERED_DATE"
from flat f, citation c, ctcitation_type_status ts, coll_object co,
(select * from media_relations where media_relationship = 'shows cataloged_item') mr
where f.collection_object_id=c.collection_object_id
and c.type_status=ts.type_status
and mr.related_primary_key(+) = f.collection_object_id
and f.collection_object_id = co.collection_object_id
and ts.category != 'Temp'
group by f.collection, ts.type_status, co.coll_object_entered_date, ts.category
</cfquery>
<cfoutput>
<cfset csv = queryToCSV(getStats)> 
<cffile action="write" file="/#application.webDirectory##filePath##targetFile#" output = "#csv#" addnewline="No">
</cfoutput>

<cftry>
	<cfexecute name = "/usr/bin/Rscript" 
		arguments = "/#application.webDirectory#/metrics/R/simple_chart.R" 
		variable = "chartOutput"
		timeout = "10000"
		errorVariable = "chartError"> 
	</cfexecute>
<cfcatch>
	<h3>Error loading chart</h3>
	<cfdump var="#cfcatch#">
	<cfset chartOutput = "">
	<cfset errorVariable="">
</cfcatch>
</cftry>
<cfoutput>
	<div class="container">
		<div class="row">
			<h1 class="h3 mt-3">Herpetology Citations</h1>
			<div class="col-12">
				<h3 class="h4 mt-1">Data Visualization Testing</h3>
				<p>Data that is imported into the R script is /metrics/datafiles/chart_data.csv and available here: <a href="#filePath##targetFile#">download table</a>.</p> This data comes from a temporary table in the database generated by a procedure and scheduled job which is then queried by CF to create the csv.
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				Script output: [#chartOutput#]
			</div>
			<div class="col-12">
				Script errors: [#chartError#]
			</div>
			<div class="col-12">
				<p> Chart that looks like a bullseye should appear.</p>
			</div>
			<div class="col-12">
				<!--- chart created by R script --->
				<img src="/metrics/R/graphs/chart1.png"/>
			</div>
		</div>
	</div>
</cfoutput>
<cfinclude template="/shared/_footer.cfm">
