<!--

* /metrics/testMetrics.cfm

Copyright 2023 President and Fellows of Harvard College

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

* Demonstration of ajax patterns in MCZbase.

-->
<cfset pageTitle="Metrics Testing">
<cfinclude template="/shared/_header.cfm">
<cfinclude template = "/shared/component/functions.cfc">

<cfset targetFile = "chart_data.csv">
<cfset filePath = "/metrics/datafiles/">
<cfset beginDate = '2022-06-30'>
<cfset endDate = '2023-07-01'>
<cfquery name="getStats" datasource="user_login" username="#session.dbuser#" password="#decrypt(session.epw,cfid)#">
SELECT rm.holdings as "HOLDINGS",h.collection as "COLLECTION",h.catalogeditems as "CATALOGED ITEMS",h.specimens as "SPECIMENS",p.primaryCatItems as "PRIMARY CATALOGED ITEMS",p.primaryspecimens as "PRIMARY SPECIMENS",s.secondaryCatItems as "Secondary Cataloged Item",s.secondarySpecimens as "Secondary Specimen"
					FROM (select collection_cde,institution_acronym,descr,collection,collection_id from collection where collection_cde <> 'MCZ' and collection <> 'Special Collections' and collection <> 'Herpetology Observations') c
					LEFT JOIN (select collection_id,holdings,reported_date from MCZBASE.collections_reported_metrics) rm on c.collection_id = rm.collection_id 
					LEFT JOIN (select f.collection_id, f.collection, count(distinct f.collection_object_id) catalogeditems, sum(decode(total_parts,null, 1,total_parts)) specimens from flat f join coll_object co on f.collection_object_id = co.collection_object_id where co.COLL_OBJECT_ENTERED_DATE < to_date('#endDate#','YYYY-MM-DD') group by f.collection_id, f.collection) h on rm.collection_id = h.collection_id
					LEFT JOIN (select f.collection_id, f.collection, ts.CATEGORY, count(distinct f.collection_object_id) primaryCatItems, sum(decode(total_parts,null, 1,total_parts)) primarySpecimens from coll_object co join flat f on co.collection_object_id = f.collection_object_id join citation c on f.collection_object_id = c.collection_object_id join ctcitation_type_status ts on c.type_status = ts.type_status where ts.CATEGORY in ('Primary') and co.COLL_OBJECT_ENTERED_DATE < to_date('#endDate#','YYYY-MM-DD') group by f.collection_id, f.collection, ts.CATEGORY) p on h.collection_id = p.collection_id
					LEFT JOIN (select f.collection_id, f.collection, ts.CATEGORY, count(distinct f.collection_object_id) secondaryCatItems, sum(decode(total_parts,null, 1,total_parts)) secondarySpecimens from coll_object co join flat f on co.collection_object_id = f.collection_object_id join citation c on f.collection_object_id = c.collection_object_id join ctcitation_type_status ts on c.type_status = ts.type_status where ts.CATEGORY in ('Secondary') and co.COLL_OBJECT_ENTERED_DATE < to_date('#endDate#','YYYY-MM-DD') group by f.collection_id, f.collection, ts.CATEGORY) s 
					on h.collection_id = s.collection_id
</cfquery>
<cfoutput>
<cfset csv = queryToCSV(getStats)> 
<cffile action="write" file="#application.webDirectory##filePath##targetFile#" output = "#csv#" addnewline="No">
</cfoutput>

<cftry>
	<cfexecute name = "/usr/bin/Rscript" 
		arguments = "#application.webDirectory#/metrics/R/simple_chart.R" 
		variable = "chartOutput"
		timeout = "10000"
		errorVariable = "chartError"> 
	</cfexecute>
<cfcatch>
	<h3>Error loading chart</h3>
	<cfdump var="#cfcatch#">
	<cfset chartOutput = "">
	<cfset errorVariable="">
</cfcatch>
</cftry>
<cfoutput>
	<div class="container">
		<div class="row">
			<h1 class="h3 mt-3">Herpetology Citations</h1>
			<div class="col-12">
				<h3 class="h4 mt-1">Data Visualization Testing</h3>
				<p>Data that is imported into the R script is /metrics/datafiles/chart_data.csv and available here: <a href="#filePath##targetFile#">download table</a>.</p> This data comes from a temporary table in the database generated by a procedure and scheduled job which is then queried by CF to create the csv.
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				Script output: [#chartOutput#]
			</div>
			<div class="col-12">
				Script errors: [#chartError#]
			</div>
			<div class="col-12">
				<p> Chart that looks like a bullseye should appear.</p>
			</div>
			<div class="col-12">
				<!--- chart created by R script --->
				<img src="/metrics/R/graphs/chart1.png"/>
			</div>
		</div>
	</div>
</cfoutput>
<cfinclude template="/shared/_footer.cfm">
